---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  vars:
    web_root: /var/www/html
    web_owner: www-data
    web_group: www-data
    service_name: apache2   # change to 'nginx' if you use Nginx

  tasks:
    - name: Ensure the web root exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ web_owner }}"
        group: "{{ web_group }}"
        mode: "0755"

    - name: Copy HTML/CSS/JS assets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ web_root }}/"
        owner: "{{ web_owner }}"
        group: "{{ web_group }}"
        mode: "0644"
      with_fileglob:
        - "*.html"
        - "*.css"
        - "*.js"
      notify: Restart web server

    - name: Copy image assets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ web_root }}/"
        owner: "{{ web_owner }}"
        group: "{{ web_group }}"
        mode: "0644"
      with_fileglob:
        - "*.jpg"
        - "*.png"
        - "*.gif"
      notify: Restart web server

  handlers:
    - name: Restart web server
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted